### ISSUE TITLE
Error: File missing from input directory path

### ISSUE THREAD

**Issue by MikeWHolloway** [waggle-sensor/data-tools#1]
I am unable to use the `dataReduction.py` tool to process some unpackaged AoT data. 

I've tested the absolute path of the unpackaged directory in the python3 interpreter but cannot get the reduction tool to work from command line. 

`os.path.exists('/home/porlando/aot/AoT_Portland.complete.2018-07-03')`
`True`

`python3 dataReduction.py -i /home/porlando/aot/AoT_Portland.complete.2018-07-03 -t 10m`
`Error: Files missing from input directory path.`

I get the same error when enveloping the absolute path in quotes as well...

`python3 dataReduction.py -i '/home/porlando/aot/AoT_Portland.complete.2018-07-03' -t 10m`
`Error: Files missing from input directory path.`

Any help is appreciated!

``

**Comment by rajeshxsankaran** [comment]
@MikeWHolloway can you give me a ls of your `/home/porlando/aot/AoT_Portland.complete.2018-07-03` directory? Is the CSV.gz file unzipped?

**Comment by MikeWHolloway** [comment]
I figured it out! The unpacked `AoT_Portland.complete.2018-07-03` created a directory called `data.csv` with the file `data.csv` nested inside. After looking through the `dataReduction.py` source, I realized that it is expecting a file and not a dir for `data.csv`. Thanks for the quick response Raj!

**Comment by rajeshxsankaran** [comment]
Sure thing. Close the issue when you succeed :).

**Comment by amorrison9796** [comment]
Glad you got it figured out!
