### ISSUE TITLE
Error: Path does not exist. Specify full path to unpackaged complete node data set

### ISSUE THREAD

**Issue by MikeWHolloway** [waggle-sensor/data-tools#2]
Another quick question regarding the reduction tool. 

I have `dataReduction.py` running on linux, but also need to process data locally on windows. :/ 

Python3 interpreter recognizes the following:
`os.path.exists('C:/Users/porlando/Desktop/AoT_Portland.complete.2018-07-03')`
`True`

However, I cannot assign the same path when calling `dataReduction.py` from the windows command line.
`python3 dataReduction.py -i 'C:/Users/porlando/Desktop/AoT_Portland.complete.2018-07-03' -t 1m`
`Error: Path does not exist. Specify full path to unpackaged complete node data set`

**Comment by rajeshxsankaran** [comment]
@MikeWHolloway Unfortunately we do not have a way to test the tools on Windows OS, and we do not want to support the platform right now.

**Comment by MikeWHolloway** [comment]
Thanks for the info and I don't blame you!
